---
title: "Flight Hours Report"
author: "MAJ Jim Pleuss"
date: "September 7, 2019"
output: pdf_document
params: 
  uic: "WDDRC0"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error=FALSE, message=FALSE)
library(tidyverse)
library(stringr)
```

## Flight Hour Summary for `r params$uic`. 


```{r }
uic="WDDRC0"
cab="82nd ABN CAB"

hours=read_csv("aircraft_hours_maintenance_competitors_v2.csv") %>% 
  mutate(model2=str_sub(Model, start = 1L, end = -2L)) %>%
  filter(!is.na(CAB) & CAB!="#N/A") %>%
  select(`Hours Flown`,model2,`As Of Date`,`Serial Number`,CAB,UIC) %>% 
  group_by(`As Of Date`) %>% mutate(Army=sum(`Hours Flown`)/n_distinct(`Serial Number`)) %>% ungroup() %>%
  group_by(`As Of Date`,CAB) %>% mutate(Brigade=sum(`Hours Flown`)/n_distinct(`Serial Number`)) %>% ungroup() %>%
  group_by(`As Of Date`,CAB,UIC) %>% mutate(Battalion=sum(`Hours Flown`)/n_distinct(`Serial Number`)) %>% ungroup() %>%
  gather(level,hrs,Army,Brigade,Battalion)


hours %>% 
  filter(UIC==params$uic) %>%
  # filter(UIC==uic) %>%
  ggplot() +
  aes(x=`As Of Date`,y=hrs, color=fct_relevel(level,"Army","Brigade","Battalion"),group=level) + 
  geom_line() + 
  geom_point() +
  labs(title=paste0("Hours Flown Per Airframe for ",params$uic,", ",hours$CAB[hours$UIC==params$uic]),color="Unit Level",x="Month",y="Hours Per Airframe")
  # labs(title=paste0("Hours Flown Per Airframe for ",uic,", ",params$cab),color="Unit Level",x="Month",y="Hours Per Airframe")

```


