---
title: "Fantasy Football"
author: "Dusty Turner"
date: "9/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

### gets and parses player data

```{r include=FALSE}
library(tidyverse)
# base = "http://fantasy.espn.com/apis/v3/games/ffl/seasons/"
# year = "2019"
# mid = "/segments/0/leagues/"
# leagueID = "89417258"
# tail = "?view=mMatchup&view=mMatchupScore"
# url = paste0(base,year,mid,leagueID,tail)

playerperformance = NULL

for (i in 1:2) {
  
base = "http://fantasy.espn.com/apis/v3/games/ffl/seasons/"
year = "2019"
mid = "/segments/0/leagues/"
leagueID = "89417258"
tail = "?view=mMatchup&view=mMatchupScore&scoringPeriodId="
# tail = "?view=mDraftDetail&view=mLiveScoring&view=mMatchupScore&view=mPendingTransactions&view=mPositionalRatings&view=mSettings&view=mTeam&view=modular&view=mNav&view=mMatchupScore&scoringPeriodId="
url = paste0(base,year,mid,leagueID,tail,i)
# url10 = paste0(base,year,mid,leagueID,tail10,i)

ESPNGet <- httr::GET(url = url)
ESPNGet$status_code
ESPNRaw <- rawToChar(ESPNGet$content)
ESPNFromJSON <- jsonlite::fromJSON(ESPNRaw)
# ESPNFromJSON %>% listviewer::jsonedit()



## players on rosters
players = 
ESPNFromJSON$teams$roster$entries %>% map("playerPoolEntry") %>% map("player") %>%
  map_df(magrittr::extract,c("id","fullName","defaultPositionId")) %>%
  mutate(id = as.character(id))

## number of rows of stats for each player
observations = 
ESPNFromJSON$teams$roster$entries %>% map("playerPoolEntry") %>% map("player") %>% map("stats")  %>% 
  flatten() %>% map_df(~count(.)) 

playervec = 
players %>%
  mutate(observations = observations$n) %>%
  uncount(observations)

PositionDF = 
  tibble(PositionId = c(1,2,3,4,5,16),
         Position = c("Quarterback","Running Back","Wide Receiver","Tight End","Kicker","Defense"))

## projections and results for players withnames
playerperformanceshort = 
ESPNFromJSON$teams$roster$entries %>% map("playerPoolEntry") %>% map("player") %>% map("stats")  %>% 
  flatten() %>% 
    map_df(magrittr::extract,c("scoringPeriodId","seasonId","statSourceId", "statSplitTypeId","id","externalId", "appliedTotal")) %>%
  mutate(Player = playervec$fullName) %>% 
  mutate(PositionId = playervec$defaultPositionId) %>% 
  left_join(PositionDF) %>%
  mutate(iteration = i)

playerperformance = bind_rows(playerperformance,playerperformanceshort)

}

playerperformance = 
playerperformance %>% 
  select(-iteration,-seasonId) %>%
  distinct() 

```

## gets team names and records

```{r}
library(tidyverse)

PlayerTeamDF = NULL

for (i in 1:2) {
  
base = "http://fantasy.espn.com/apis/v3/games/ffl/seasons/"
year = "2019"
mid = "/segments/0/leagues/"
leagueID = "89417258"
tail10 = "?view=mMatchup&view=mMatchupScore&scoringPeriodId="
tail = "?view=mDraftDetail&view=mLiveScoring&view=mMatchupScore&view=mPendingTransactions&view=mPositionalRatings&view=mSettings&view=mTeam&view=modular&view=mNav&view=mMatchupScore&scoringPeriodId="
url = paste0(base,year,mid,leagueID,tail,i)
url10 = paste0(base,year,mid,leagueID,tail10,i)

ESPNGet <- httr::GET(url = url)
ESPNGet$status_code
ESPNRaw <- rawToChar(ESPNGet$content)
ESPNFromJSON2 <- jsonlite::fromJSON(ESPNRaw)
# ESPNFromJSON2 %>% listviewer::jsonedit()

Sys.sleep(time = runif(1,2,4))

ESPNGet10 <- httr::GET(url = url10)
ESPNGet10$status_code
ESPNRaw10 <- rawToChar(ESPNGet10$content)
ESPNFromJSON10 <- jsonlite::fromJSON(ESPNRaw10)
# ESPNFromJSON10 %>% listviewer::jsonedit()

playerrosterslot = 
ESPNFromJSON10$teams$roster$entries %>% 
  map_df(`[`,"lineupSlotId")

assignedpositions =
ESPNFromJSON10$teams$roster$entries %>% 
  map("playerPoolEntry") %>% map("player") %>% 
  map_df(magrittr::extract,c("id","fullName","defaultPositionId"))

TeamPlayers = 
ESPNFromJSON10$teams$roster$entries %>% map("playerPoolEntry") %>%
  map_df(~count(.)) 

PlayerTeamDFshort = 
ESPNFromJSON2$teams %>% select(location, nickname,id) %>%
  unite(Team, c(location,nickname)) %>%
  mutate(TeamPlayers = TeamPlayers$n) %>% 
  uncount(TeamPlayers) %>%
  mutate(Player = assignedpositions$fullName) %>%
  select(-id) %>% 
  mutate(playerrosterslot = playerrosterslot$lineupSlotId) %>%
  mutate(scoringPeriodId = i)

PlayerTeamDF = bind_rows(PlayerTeamDF,PlayerTeamDFshort)

}
```


## adds team info to player dataframe

```{r}

PlayerPerformance = 
playerperformance %>%
  left_join(PlayerTeamDF, by = c("Player","scoringPeriodId")) %>%
  as_tibble()

PlayerSlotIDs = tibble(playerrosterslot = c(0,2,4,6,16,17,20,21,23),
                       SlottedPosition = c("Quarterback", "Running Back", "Wide Receiver", "Tight End", "Defense", "Kicker", "Bench", "IR", "Flex"))
  

WeeklyEstimates =
PlayerPerformance %>% as.data.frame() %>%
  # filter(Team == "'R'm Chair_Quarterback") %>%
  filter(nchar(externalId) > 4) %>%
  mutate(statSourceId = if_else(statSourceId==1, "Predicted", "Actual")) %>%
  select(scoringPeriodId,statSourceId,appliedTotal,Player,Position,Team,playerrosterslot) %>%
  spread(statSourceId, appliedTotal) %>% 
  arrange(Player) %>%
  # filter(!is.na(Actual)) %>%
  mutate(ActualMinusPredicted = Actual-Predicted) %>% 
  left_join(PlayerSlotIDs) %>% 
  # filter(scoringPeriodId==1)
  # select(-playerrosterslot) %>%
  mutate(Starter = if_else(SlottedPosition %in% c("Bench", "IR"), "Bench", "Starter"))
```


### analysis on created dataframe

```{r}
WeeklyEstimates %>%
  arrange(-ActualMinusPredicted) %>%
  group_by(Team, scoringPeriodId) %>%
  summarise(MeanActualMinusPredicted = mean(ActualMinusPredicted, na.rm = TRUE)) %>%
  arrange(scoringPeriodId)

WeeklyEstimates %>%
  filter(Starter=="Starter") %>%
  filter(!is.na(ActualMinusPredicted)) %>%
  group_by(Team, scoringPeriodId, Starter) %>% 
  # filter(Team == "'R'm Chair_Quarterback") %>% arrange(Starter) %>%
  summarise(TeamActual = sum(Actual),
            TeamPredicted = sum(Predicted)) %>%
  mutate(TeamActualMinusPredicted = TeamActual-TeamPredicted) %>%
  ggplot(aes(x=TeamPredicted,y=TeamActual, color = TeamActualMinusPredicted)) +
  geom_point() +
  geom_abline() +
  xlim(95,160) +   ylim(95,160) +
  ggrepel::geom_text_repel(aes(label = Team), max.iter = 10000) +
  labs(x="Predicted Points Scored", y="Actual Points Scored", title = "Projected vs Actual Points Scored in Week 1", color = "Actual-Predicted") 
  # facet_wrap(~Starter) 

WeeklyEstimates %>%
  filter(!is.na(ActualMinusPredicted)) %>%
  group_by(Team, scoringPeriodId, Starter) 


WeeklyEstimates %>% as_tibble() %>% 
  filter(!is.na(ActualMinusPredicted)) %>%
  ggplot(aes(x=ActualMinusPredicted)) +
  geom_histogram()

WeeklyEstimates %>% as_tibble() %>% 
  filter(!is.na(ActualMinusPredicted)) %>%
  ggplot(aes(x=Predicted,y=Actual)) +
  geom_point() +
  geom_smooth(method = "lm")

WeeklyEstimates %>% as_tibble() %>% 
  filter(!is.na(ActualMinusPredicted)) %>%
  ggplot(aes(x=ActualMinusPredicted)) +
  geom_histogram(binwidth = 5) +
  facet_wrap(~Position, ncol = 1) +
  geom_vline(aes(xintercept = 0, color = "red")) +
  theme(legend.position = "none")

WeeklyEstimates %>% as_tibble() %>% 
  filter(!is.na(ActualMinusPredicted)) %>%
  ggplot(aes(x=Predicted,y=Actual, color = Team)) +
  geom_point() +
  # facet_grid(Starter~Team) +
  # facet_wrap(~Team, ncol = 2) +
  geom_abline(aes(slope =1, intercept = 0),color = "red")
  # theme(legend.position = "none")


```

## Gets team records

```{r}
base = "http://fantasy.espn.com/apis/v3/games/ffl/seasons/"
year = "2019"
mid = "/segments/0/leagues/"
leagueID = "89417258"
# tail10 = "?view=mMatchup&view=mMatchupScore&scoringPeriodId="
# tail = "?view=mDraftDetail&view=mLiveScoring&view=mMatchupScore&view=mPendingTransactions&view=mPositionalRatings&view=mSettings&view=mTeam&view=modular&view=mNav&view=mMatchupScore&scoringPeriodId="
tail = "?&view=mMatchupScore&scoringPeriodId="
url = paste0(base,year,mid,leagueID,tail)
# url10 = paste0(base,year,mid,leagueID,tail10,i)

ESPNGet <- httr::GET(url = url)
ESPNGet$status_code
ESPNRaw <- rawToChar(ESPNGet$content)
ESPNFromJSON2 <- jsonlite::fromJSON(ESPNRaw)
# ESPNFromJSON2 %>% listviewer::jsonedit()

teamiddf = tibble(
  id = c(1:10),
  team = c("'R'm Chair Quarterback", "Philly Chapmaniacs", "The Plainsmen", "The OBJective Functions", "Analysis Paralysis", 
           "Team Ward", "Compute This!", "The Chief", "Dallas The boys", "Palindrome Tikkit")
)

season = tibble(
awayid = ESPNFromJSON2$schedule$away$teamId,
awaypoints = ESPNFromJSON2$schedule$away$totalPoints,
homeid = ESPNFromJSON2$schedule$home$teamId,
homepoints = ESPNFromJSON2$schedule$home$totalPoints,
winner = ESPNFromJSON2$schedule$winner,
weekID = ESPNFromJSON2$schedule$matchupPeriodId
) %>%
  left_join(teamiddf, by = c("awayid"="id")) %>%
  rename(AwayTeam = team) %>%
  left_join(teamiddf, by = c("homeid"="id")) %>%
  rename(HomeTeam = team) %>%
  mutate(winner = if_else(awaypoints>homepoints,AwayTeam,HomeTeam))
  

season

season %>% select(-awayid,-homeid) %>%
  gather(Location, Points, -winner, -weekID, -AwayTeam,-HomeTeam) %>%
  arrange(weekID) %>%
  group_by(weekID) %>%
  mutate(rank = rank(-Points)) %>%
  mutate(EWETL = rank-1) %>%
  mutate(EWETW = 10-rank) %>%
  group_by()
  
```
