---
title: "Python_in_R"
author: "Dusty Turner"
date: "8/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(reticulate)
```


```{python}
import numpy as np
my_python_array = np.array([2,4,6,8])
for item in my_python_array:
    print(item)
    

import requests

league_id = 1314476
year = 2018
# url = "https://fantasy.espn.com/apis/v3/games/ffl/leagueHistory/" + \
#       str(league_id) + "?seasonId=" + str(year)
# url = "http://fantasy.espn.com/apis/v3/games/ffl/seasons/2018/segments/0/leagues/1314476?view=mDraftDetail&view=mLiveScoring&view=mMatchupScore&view=mPendingTransactions&view=mPositionalRatings&view=mSettings&view=mTeam&view=modular&view=mNav"
url = "http://fantasy.espn.com/apis/v3/games/ffl/seasons/2019/segments/0/leagues/89417258?view=mDraftDetail&view=mLiveScoring&view=mMatchupScore&view=mPendingTransactions&view=mPositionalRatings&view=mSettings&view=mTeam&view=modular&view=mNav&view=mMatchupScore"
url = "http://fantasy.espn.com/apis/v3/games/ffl/seasons/2018/segments/0/leagues/1314476?view=mMatchupScore"

r = requests.get(url)
# d = r.json()[0]    
d = r.json()    

# r = requests.get(url, params={"view": "mMatchup"})
# r.json()

df = [[
        game['matchupPeriodId'],
        game['home']['teamId'], game['home']['totalPoints'],
        game['away']['teamId'], game['away']['totalPoints']
    ] for game in d['schedule']]
df = pd.DataFrame(df, columns=['Week', 'Team1', 'Score1', 'Team2', 'Score2'])
df['Type'] = ['Regular' if w<=14 else 'Playoff' for w in df['Week']]
df.head()
```

```{r}
    ## records
  py$d$teams %>% map_df(magrittr::extract, c("location", "nickname", "id")) %>% bind_cols(
    py$d$teams %>% map("record") %>% map("overall") %>% map_df(magrittr::extract, c("losses", "wins"))
  )

    ## schedule below    
py$d$schedule %>% map_df(magrittr::extract, c("winner","matchupPeriodId")) %>% 
  bind_cols(py$d$schedule %>% map("away") %>% map_df(magrittr::extract,c("teamId","totalPoints"))) %>%
  bind_cols(py$d$schedule %>% map("home") %>% map_df(magrittr::extract,c("teamId","totalPoints")))

```


```{r}
library(tidyverse)
library(purrr)


  py$d$schedule %>% listviewer::jsonedit()
  py$d$teams %>% listviewer::jsonedit()
  # py$d$schedule %>% map("matchupPeriodId")
  # py$d$schedule %>% map("winner") 
  # py$d$schedule %>% map("away") %>% map("teamId") 
  # py$d$schedule %>% map("away") %>% map("totalPoints") 
  # py$d$schedule %>% map("home") %>% map("teamId") 
  # py$d$schedule %>% map("home") %>% map("totalPoints") 

  py$d$teams %>% map_df(magrittr::extract, c("location", "nickname", "id",))
    py$d$teams %>% map_df(magrittr::extract, c("location", "nickname", "id"))
    
  # py$d$schedule %>% map_df(magrittr::extract, c("winner","matchupPeriodId")) 
  
    # py$d$schedule %>% map("away") %>% map_df(magrittr::extract,c("teamId","totalPoints")) 

    ## records
  py$d$teams %>% map_df(magrittr::extract, c("location", "nickname", "id")) %>% bind_cols(
    py$d$teams %>% map("record") %>% map("overall") %>% map_df(magrittr::extract, c("losses", "wins"))
  )

    ## schedule below    
py$d$schedule %>% map_df(magrittr::extract, c("winner","matchupPeriodId")) %>% 
  bind_cols(py$d$schedule %>% map("away") %>% map_df(magrittr::extract,c("teamId","totalPoints"))) %>%
  bind_cols(py$d$schedule %>% map("home") %>% map_df(magrittr::extract,c("teamId","totalPoints")))
  

```



